name: Paradigm Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore ./src/Paradigm.Core.sln
    - name: Build
      run: dotnet build ./src/Paradigm.Core.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Paradigm.Core.sln --no-restore --verbosity normal