name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/Paradigm.Core.sln

      - name: Build
        run: dotnet build  ./src/Paradigm.Core.sln -c Release --no-restore

      - name: Test
        run: dotnet test ./src/Paradigm.Core.sln -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
